#!/bin/sh

. git-sh-setup

show()
{
  sha=$1
  type=$(git cat-file -t $sha)
  echo $sha $type
}

find -E "$GIT_DIR/objects" -type f -regex '.*[0-9a-f]{2}/[0-9a-f]{38}' | while read object
do
  dir=$(dirname "$object")
  show $(basename "$dir")$(basename "$object")
done

find "$GIT_DIR/objects/pack/" -name '*.idx' | while read pack
do
  git show-index < "$pack" | cut -f 2 -d ' ' | while read sha
  do
    show $sha
  done
done
