#!/bin/sh

. /opt/local/libexec/git-core/git-sh-setup

show()
{
  sha=$1
  type=$(git cat-file -t $sha)
  echo $sha $type
}

for object in `find -E $GIT_DIR/objects -type f -regex '.*[0-9a-f]{2}/[0-9a-f]{38}'`
do
  show $(echo $object | sed -e s@$GIT_DIR/objects/@@ | cut -c 1-2,4-)
done

for pack in `find $GIT_DIR/objects/pack/ -name '*.idx'`
do
  for sha in `git show-index < $pack | cut -f 2 -d ' '`
  do
    show $sha
  done
done
